name: project2
channels: !!python/tuple
- anaconda-fusion
- conda-forge
- defaults
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py35_0
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::cython=0.25.2=py35_1
- conda-forge::freetype=2.7=1
- conda-forge::h5py=2.6.0=np112py35_7
- conda-forge::hdf5=1.8.17=9
- conda-forge::jasper=1.900.1=4
- conda-forge::jpeg=9b=0
- conda-forge::libgfortran=3.0.0=1
- conda-forge::libpng=1.6.28=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::matplotlib=2.0.0=np112py35_2
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.0=py35_blas_openblas_200
- conda-forge::openblas=0.2.19=1
- conda-forge::openssl=1.0.2h=3
- conda-forge::pip=9.0.1=py35_0
- conda-forge::pyparsing=2.2.0=py35_0
- conda-forge::python=3.5.3=1
- conda-forge::python-dateutil=2.6.0=py35_0
- conda-forge::pytz=2016.10=py35_0
- conda-forge::readline=6.2=0
- conda-forge::scipy=0.19.0=np112py35_blas_openblas_200
- conda-forge::setuptools=33.1.0=py35_0
- conda-forge::six=1.10.0=py35_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::tornado=4.4.2=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zlib=1.2.11=0
- pip:
  - appdirs==1.4.3
  - keras==1.2.2
  - opencv-python==3.2.0.6
  - packaging==16.8
  - protobuf==3.2.0
  - pyyaml==3.12
  - theano==0.8.2
  - https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.1-py3-none-any.whl

